version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASS}
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASS}
      MYSQL_TCP_PORT: ${SQL_PORT}
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
    restart: always

  redis:
    logging:
      driver: none
    image: redis
    restart: always
    command: redis-server
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ${REDIS_DIR}:/data

  realistikgdps:
    image: realistikgdps:latest
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - mysql
      - redis
      - meilisearch
    restart: always
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_URL_PREFIX=${HTTP_URL_PREFIX}
      - SQL_USER=${SQL_USER}
      - SQL_PASS=${SQL_PASS}
      - SQL_HOST=${SQL_HOST}
      - SQL_DB=${SQL_DB}
      - SQL_PORT=${SQL_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - MEILI_HOST=${MEILI_HOST}
      - MEILI_PORT=${MEILI_PORT}
      - MEILI_KEY=${MEILI_KEY}
      - SERVICE_READINESS_TIMEOUT=${SERVICE_READINESS_TIMEOUT}
      - SRV_NAME=${SRV_NAME}
      - SRV_COMMAND_PREFIX=${SRV_COMMAND_PREFIX}
      - S3_ENABLED=${S3_ENABLED}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - LOCAL_ROOT=/data # NOTE: Ensure this matches the volume mount below.
      - APP_COMPONENT=${APP_COMPONENT:-api}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOGZIO_ENABLED=${LOGZIO_ENABLED}
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
    volumes:
      - .:/app
      - ${RGDPS_DIR}:/data

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - "${MEILI_PORT}:${MEILI_PORT}"
    volumes:
      - ${MEILI_DIR}:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_KEY}
      - MEILI_HTTP_ADDR=0.0.0.0:${MEILI_PORT}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_HOST=${SQL_HOST}
      - PMA_PORT=${SQL_PORT}
      - UPLOAD_LIMIT=500M
    depends_on:
      - mysql
